# Generated by Django 2.1 on 2019-10-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Item'),
            preserve_default=False,
        ),
    ]
