# Generated by Django 2.1 on 2019-10-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191018_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
        migrations.AddField(
            model_name='product',
            name='itemize',
            field=models.CharField(default='good', max_length=40),
            preserve_default=False,
        ),
    ]
