# Generated by Django 2.1 on 2019-10-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191018_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='itemize',
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Item'),
            preserve_default=False,
        ),
    ]
